### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by WoleFabikun** [TonicAI/tonic_ragas_logger#1]
Is this able for use now? I keep getting 500 errors and I followed the instructions given exactly.

**Comment by akamor** [comment]
@WoleFabikun We are looking into this.  In the meantime, you can also use our tonic-validate SDK if you wish to begin visualizing metrics immediately.

**Comment by ethan-tonic** [comment]
@WoleFabikun I think we found the issue. Should have a patch out tomorrow for it.

**Comment by ethan-tonic** [comment]
@WoleFabikun v1.2.0 fixes this issue

**Comment by ethan-tonic** [comment]
Also, it seems it was partially due to a backend issue which fixes the issue even on older versions of the tonic_ragas_logger. But I would upgrade still as there are some other issues I fixed
